server:
  port: 80
  forward-headers-strategy: native
  undertow:
    threads:
      worker: 2
      io: 2
spring:
  datasource:
    username: bup
    password: bup
    url: jdbc:mysql://mysql:3306/bup?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始化配置
      initial-size: 1
      # 最小连接数
      min-idle: 1
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: mwxmmy
        login-password: mwxmmy
        allow:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          #为spring data jpa saveAll方法提供批量插入操作 此处可以随时更改大小 建议500哦
          batch_size: 1000
          batch_versioned_data: true
          order_inserts: true
  thymeleaf:
    cache: false
  task:
    scheduling:
      pool:
        size: 10
#  h2:
#    console:
#      enabled: true

record:
  userName:
  password:
  work-path: /bilirecord
  wx-push-token: AT_oboGsjlaGphljfVS9TtC7JfuBB0xPJrn

logging:
  file:
    path: ${record.work-path}/log/
  logback:
    rollingpolicy:
      max-file-size: 50MB

